# Generated by Django 4.0.3 on 2022-05-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kniha',
            name='autor',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kniha',
            name='recenze',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
